### ISSUE TITLE
[1.12.2-1.0.6] Obsidian recipe should use logs instead of planks

### ISSUE THREAD

**Issue by Compegen** [modmuss50/Retro-Exchange#1]
The current recipe `retroexchange:obsidian` uses 2 wooden planks to make 1 obsidian. Following EMC rules in ProjectE, this would be 8 EMC per plank to Obsidians 64 EMC. Logs have an EMC of 32, meaning 2 logs would be the equivilant of 1 Obsidian.

**Comment by Prospector** [comment]
Still an issue on the 1.14 fabric version

**Comment by modmuss50** [comment]
Fixed in the next version.
