### ISSUE TITLE
retroexchange is dysfunctional in 1.14.1(and possibly 2)

### ISSUE THREAD

**Issue by Yoghurt4C** [modmuss50/Retro-Exchange#10]
this time it's bork on both the client and the server

**Comment by TimGoll** [comment]
Are you talking about this?
`Tried to load unrecognized recipe: retroexchange:transmution_id_9 removed now.`
because it stopped working for me too

**Comment by Julian-MM** [comment]
It works for me, on 1.14.1, however the 4 iron & transmutation stone recipe has multiple items it should make, but it only leads to making gold, which is a shame as the only reason i was eager to get one was to craft iron into enderpearls

**Comment by modmuss50** [comment]
fixed in the next version.
