### ISSUE TITLE
Enderpearl exchange conflict

### ISSUE THREAD

**Issue by Brandcraf06** [modmuss50/Retro-Exchange#11]
The recipe for make enderpearl and for make gold are the same, and the golden one takes over.
![image](https://user-images.githubusercontent.com/16505254/58387303-de5b5080-800c-11e9-9449-b86f9d7a6d59.png)

**Comment by Knito58** [comment]
Same for me. Found the transmutation.json in the data folder and now it uses clay (blocks)  for the enderpearls.

**Comment by modmuss50** [comment]
Fixed in the next version.
