### ISSUE TITLE
Gold ore smelting

### ISSUE THREAD

**Issue by CrimsonTyphon** [modmuss50/Retro-Exchange#7]
Gold doesn't have a crafting recipe to turn ore into ingots, just thought I should mention that.

**Comment by modmuss50** [comment]
![](https://ss.modmuss50.me/java_2019-05-12_12-14-03.png)
![](https://ss.modmuss50.me/java_2019-05-12_12-14-38.png)

humm, seems to be working,

**Comment by modmuss50** [comment]
oh smelting

**Comment by modmuss50** [comment]
![](https://ss.modmuss50.me/java_2019-05-12_12-15-50.png)

**Comment by modmuss50** [comment]
Fixed in the next version.
